### ISSUE TITLE
reporover program doesn't seem to be added to PATH after install on Windows

### ISSUE THREAD

**Issue by jwenskovitch** [keggster101020/Repo-Rover#10]
Running Windows 7 with Python 2.7

```
C:\BTSync\Allegheny\280\Repo-Rover>reporover
'reporover' is not recognized as an internal or external command,
operable program or batch file.

C:\BTSync\Allegheny\280\Repo-Rover>cd build\lib\repo_rover\
C:\BTSync\Allegheny\280\Repo-Rover\build\lib\repo_rover>python reporover.py

*starts running now*
```

**Comment by keggster101020** [comment]
This might be an issue with how Windows handles integration of of external programs into its shell. But will require further investigation. 

Thanks

**Comment by mccurdyc** [comment]
Unfortunately jwenskovitch, the install script doesn't handle managing your system's path. This will need to be set on a per-system basis. We address this to users in commit [dd2ff9f](https://github.com/keggster101020/Repo-Rover/commit/dd2ff9ff4afcade4b83ee389fc3647e64ee33979). Please refer to the new [README](https://github.com/keggster101020/Repo-Rover).

Sorry.
