### ISSUE TITLE
System Testing on Home Directory

### ISSUE THREAD

**Issue by victorzhz** [keggster101020/Repo-Rover#12]
@gkapfham Could you please run our program to help our system testing? If it is possible, could you run the program on the home directory three times and report back including amount of Git repositories found in how long it took to complete? 

Thank you!

Victor and Jacob

**Comment by burdetp** [comment]
Six git repos were found, only one of which had uncommitted changes.
Timing:
        0.57 real         0.31 user         0.26 sys
        0.60 real         0.32 user         0.26 sys
        0.58 real         0.32 user         0.26 sys
