### ISSUE TITLE
Link missing in README.md.

### ISSUE THREAD

**Issue by kauffmj** [keggster101020/Repo-Rover#4]
In the following section you mention that you are providing a link to a "wonderful git tutorial" but then never provide the link:

https://github.com/keggster101020/Repo-Rover.git

**Comment by mccurdyc** [comment]
Thank you kauffmj the [link](https://try.github.io/levels/1/challenges/1) is now included in the README! Check it out [here](https://github.com/keggster101020/Repo-Rover)!
