### ISSUE TITLE
Add reporting for untracked files.

### ISSUE THREAD

**Issue by deedoubledub** [keggster101020/Repo-Rover#5]
Repo-Rover reports 'No issues' for repositories that contain untracked files.

```
$ cd git-repo
$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        newfile

nothing added to commit but untracked files present (use "git add" to track)
$~/.local/bin/reporover ~/git
I found 7 git repositories.
...
/home/user/git-repo:  No issues.
Repos 100% clean.
```

**Comment by mccurdyc** [comment]
Thank you deedoubledub, we will resolve this issue shortly

**Comment by mccurdyc** [comment]
We aren't going to add this feature because it would make a lot of repositories seem "dirty" when it reality, the core files have been pushed. A lot of users tend to omit a .gitignore and therefore sometimes makes their repositories look "dirty".

**Comment by deedoubledub** [comment]
Repos with untracked files **are** _dirty_.

The .gitignore should be committed to the repo or ignored in a committed .gitignore. Other things that should be ignored, that you don't want to be in a repo-specific .gitignore should be ignored in a global gitignore.
