### ISSUE TITLE
Error with running setup.py script on Windows.

### ISSUE THREAD

**Issue by kauffmj** [keggster101020/Repo-Rover#6]
I was able to successfully clone the repository under Windows, but when I try to run the setup.py script I get an error and the installation is not successful.  Here is the way in which I invoked the setup.py script:

`python setup.py install`

This is the output that I saw:

running install
running build
running build_py
running build_scripts
running install_lib
byte-compiling C:\Python34\Lib\site-packages\repo_rover\reporover.py to reporover.cpython-34.pyc
running install_scripts
running install_egg_info
Removing C:\Python34\Lib\site-packages\repo_rover-1.0-py3.4.egg-info
Writing C:\Python34\Lib\site-packages\repo_rover-1.0-py3.4.egg-info
**Sorry: TabError: inconsistent use of tabs and spaces in indentation (reporover.py, line 44)**

Here is all of the relevant information about OS and software versions, please let me know if you need any additional information to debug the issue:
- OS: Windows 7 Enterprise, SP 1, 64-bit
- Python: Version 3.4.3, 32-bit
- Git: Version 2.5.0.windows.1, 64-bit

**Comment by mccurdyc** [comment]
Hello kauffmj, were you then able to use Repo-Rover after installing it using `python setup.py install`?

**Comment by kauffmj** [comment]
No, when I run `reporover` at the command prompt I see an error saying that the command was not found:

'reporover' is not recognized as an internal or external command,
operable program or batch file.

**Comment by keggster101020** [comment]
Hi kauffmj, can you please post in lines 37-45 of the code located in the `repo_rover/reporover.py` file. 
Thank you

**Comment by kauffmj** [comment]
Sure:

```
def find_git_repos(dir):
    global totalRepos;
    repos = []
    for (path, dirs, files) in os.walk(dir):
        for directory in dirs:
            if directory == ".git":
                repos.append(path)
        totalRepos=totalRepos+1;
    return repos
```
