### ISSUE TITLE
Style missing from web report.

### ISSUE THREAD

**Issue by deedoubledub** [keggster101020/Repo-Rover#7]
On the very first run of Repo-Rover, a proper web report was generated. On every subsequent run, even after a full removal and rebuild, the CSS files are missing from the web report. I have even started from scratch with a different user account on a different system without ever seeing the CSS files properly generated.

```
$ ls /tmp/tmp1vSqoF
index.html
```

**Comment by deedoubledub** [comment]
Upon further investigation I have discovered that the CSS files are not generated when all repositories are clean. Having a repo with issues properly triggers the CSS to be generated.

**Comment by mccurdyc** [comment]
We will look into generating the CSS in a clean repository, or not at all.

**Comment by deedoubledub** [comment]
This issue has not been fixed.

**Comment by keggster101020** [comment]
You noted earlier that the CSS is not generated when there is no issues with repos. This is part of the design of the system in that no web report will be generated if there is nothing to report on (ie: all your repositories are clean)

**Comment by mccurdyc** [comment]
We will resolve this issue keggster101020 is just going to omit opening a browser tab for a clean repository
