### ISSUE TITLE
Unable to run setup.py

### ISSUE THREAD

**Issue by msaperst** [keggster101020/Repo-Rover#8]
After following instructions in readme.md, I am unable to run setup.py.
I get the below error after following your steps

F:\git>git clone https://github.com/keggster101020/Repo-Rover.git
Cloning into 'Repo-Rover'...
remote: Counting objects: 370, done.
remote: Compressing objects: 100% (243/243), done.
rRemote: Total 370 (delta 156), reused 324 (delta 110), pack-reused 0eceiving ob
Receiving objects:  86% (319/370), 820.00 KiB | 528 KiB/s
Receiving objects: 100% (370/370), 949.10 KiB | 528 KiB/s, done.
Resolving deltas: 100% (156/156), done.

F:\git>python --version
Python 2.7.3

F:\git>python setup.py install
python: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by mccurdyc** [comment]
Hello msaperst, can I request that you supply more information about your system configuration? Primarily Operating System so that we can address this issue. Thank you.

**Comment by mccurdyc** [comment]
msaperst, we are going to close this issue since it has been 24-hours without a response. Please reopen this issue if it still occurs. I do want to point out that we do not support Windows (e.g. setting your PATH and other stuff).
