### ISSUE TITLE
Cannot clone repository due to publickey permission denial

### ISSUE THREAD

**Issue by jwenskovitch** [keggster101020/Repo-Rover#9]
```
jwenskovitch@aldenv114:~/280_projects$ git clone git@github.com:keggster101020/Repo-Rover.git
Cloning into 'Repo-Rover'...
The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.131' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

The repository path should be correct; I copied and pasted it straight from the README.md file.  I did not have this issue with the other two class projects.

**Comment by mccurdyc** [comment]
Hello jwenskovitch, would you mind try cloning our system with HTTPS (`git clone https://github.com/keggster101020/Repo-Rover.git`) instead of SSH? Thank you. Please let us know if this works for you!

**Comment by jwenskovitch** [comment]
Yes, that worked.  Probably an option that you should add to the README.

**Comment by mccurdyc** [comment]
I will do that, thank you for the suggestion!
